DROP EXTERNAL TABLE <NOME TABELLA ESTERNA>;
CREATE EXTERNAL TABLE <NOME TABELLA ESTERNA>
(
	<NOME_COLONNA_1> <TIPO_COLONNA_1>,
	...
	<NOME_COLONNA_N> <TIPO_COLONNA_N>
)
WITH(
	DATA_SOURCE = [<DATA SOURCE>],
	LOCATION = N'<PATH HDFS IN CUI RISIEDONO I FILE>',
	FILE_FORMAT = [<FORMATO FILE>],
	REJECT_TYPE = VALUE,
	REJECT_VALUE = 0
);